### ISSUE TITLE
Compatibility with  open JDK 11

### ISSUE THREAD

**Issue by maheshkumar93** [magro/kryo-serializers#107]
I was getting the below error after upgrading jdk from jdk1.8 to openjdk11.

2018-12-27 01:41:46.091 WARNING de.javakaffee.web.msm.BackupSessionTask call - FAILED for session id E5A2461A19812ACC2E9B47E575CFD4D2
java.lang.RuntimeException: java.lang.NoSuchFieldException: parentOffset
	at de.javakaffee.kryoserializers.SubListSerializers$ArrayListSubListSerializer.<init>(SubListSerializers.java:105)
	at de.javakaffee.kryoserializers.SubListSerializers$ArrayListSubListSerializer.addDefaultSerializer(SubListSerializers.java:121)
	at de.javakaffee.kryoserializers.SubListSerializers.addDefaultSerializers(SubListSerializers.java:78)
	at de.javakaffee.web.msm.serializer.kryo.KryoTranscoder$2.create(KryoTranscoder.java:127)
	at com.esotericsoftware.kryo.pool.KryoPoolQueueImpl.borrow(KryoPoolQueueImpl.java:51)
	at de.javakaffee.web.msm.serializer.kryo.KryoTranscoder.serializeAttributes(KryoTranscoder.java:224)
	at de.javakaffee.web.msm.TranscoderService.serializeAttributes(TranscoderService.java:151)
	at de.javakaffee.web.msm.BackupSessionTask.serializeAttributes(BackupSessionTask.java:180)
	at de.javakaffee.web.msm.BackupSessionTask.call(BackupSessionTask.java:110)
	at de.javakaffee.web.msm.BackupSessionTask.call(BackupSessionTask.java:51)
	at de.javakaffee.web.msm.BackupSessionService$SynchronousExecutorService.submit(BackupSessionService.java:347)
	at de.javakaffee.web.msm.BackupSessionService.backupSession(BackupSessionService.java:206)
	at de.javakaffee.web.msm.MemcachedSessionService.backupSession(MemcachedSessionService.java:1089)
	at de.javakaffee.web.msm.RequestTrackingHostValve.backupSession(RequestTrackingHostValve.java:230)
	at de.javakaffee.web.msm.RequestTrackingHostValve.invoke(RequestTrackingHostValve.java:159)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:104)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1137)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NoSuchFieldException: parentOffset
	at java.base/java.lang.Class.getDeclaredField(Class.java:2412)
	at de.javakaffee.kryoserializers.SubListSerializers$ArrayListSubListSerializer.<init>(SubListSerializers.java:99)
	... 24 more
I am using below version of jar..
kryo-serializers-0.37.jar
Tomcat 7.0.92
memcached-session-manager-tc7-1.8.1.jar
Please help on this

**Comment by magro** [comment]
Fixed with #106, released with kryo-serializers 0.45
