### ISSUE TITLE
Unable to use SubListSerializers with JDK9

### ISSUE THREAD

**Issue by Syed-SnapLogic** [magro/kryo-serializers#112]
I am on JDK 9 and I wrote a test as follows:

```
@Test
    public void testCustom() throws Exception {
        SubListSerializers.JavaUtilSubListSerializer s = new SubListSerializers.JavaUtilSubListSerializer();
        System.out.println(s.toString());
    }
```

I am getting the following exception:
```
[ERROR] Tests run: 382, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.567 s <<< FAILURE! - in TestSuite
[ERROR] testCustom(de.javakaffee.kryoserializers.SubListSerializersTest)  Time elapsed: 0.01 s  <<< FAILURE!
java.lang.RuntimeException: java.lang.ClassNotFoundException: java.util.SubList
	at de.javakaffee.kryoserializers.SubListSerializersTest.testCustom(SubListSerializersTest.java:178)
Caused by: java.lang.ClassNotFoundException: java.util.SubList
	at de.javakaffee.kryoserializers.SubListSerializersTest.testCustom(SubListSerializersTest.java:178)
```

Can you pls help me resolve this issue?  This is a blocker for me.

**Comment by Syed-SnapLogic** [comment]
@magro, can you or someone from your team pls reply to my question?  I am presently blocked.  Please treat this issue as a priority.

**Comment by Syed-SnapLogic** [comment]
I am sorry, this is not an issue.  Based on the JDK, I have to use the respective serializers.  I am closing it.
