### ISSUE TITLE
spark serialization error during kryo.readObject when using UnmodifieableCollectionsSerializer

### ISSUE THREAD

**Issue by shkr** [magro/kryo-serializers#28]
Serialization trace:
suppressedExceptions (com.package.SomeClass)
	at com.esotericsoftware.kryo.serializers.FieldSerializer$ObjectField.read(FieldSerializer.java:626)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:221)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:729)
	at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:134)
	at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:17)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:729)
	at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:134)
	at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:17)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:729)
	at org.apache.spark.serializer.KryoDeserializationStream.readObject(KryoSerializer.scala:142)
	at org.apache.spark.broadcast.TorrentBroadcast$.unBlockifyObject(TorrentBroadcast.scala:216)
	at org.apache.spark.broadcast.TorrentBroadcast$$anonfun$readBroadcastBlock$1.apply(TorrentBroadcast.scala:177)
	at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:1000)
	... 18 more
Caused by: java.lang.NullPointerException
	at java.util.Collections$UnmodifiableCollection.<init>(Collections.java:1051)
	at java.util.Collections$UnmodifiableList.<init>(Collections.java:1204)
	at java.util.Collections.unmodifiableList(Collections.java:1190)
	at de.javakaffee.kryoserializers.UnmodifiableCollectionsSerializer$UnmodifiableCollection$2.create(UnmodifiableCollectionsSerializer.java:115)
	at de.javakaffee.kryoserializers.UnmodifiableCollectionsSerializer.read(UnmodifiableCollectionsSerializer.java:72)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:648)
	at com.esotericsoftware.kryo.serializers.FieldSerializer$ObjectField.read(FieldSerializer.java:605)
	... 30 more

**Comment by magro** [comment]
Can you provide a self contained test (or a data structure) that allows me to reproduce this issue?
