### ISSUE TITLE
Unable to find class

### ISSUE THREAD

**Issue by icode** [magro/kryo-serializers#36]
```
com.esotericsoftware.kryo.KryoException: Unable to find class: ameba.http.session.SessionStorejava.lang.String
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:156) ~[kryo-3.0.1.jar:na]
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:133) ~[kryo-3.0.1.jar:na]
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:667) ~[kryo-3.0.1.jar:na]
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:778) ~[kryo-3.0.1.jar:na]
	at ameba.cache.util.KryoSerializer$3.execute(KryoSerializer.java:87) ~[ameba-cache-core-0.1.7-20150612.185233-88.jar:na]
	at com.esotericsoftware.kryo.pool.KryoPoolQueueImpl.run(KryoPoolQueueImpl.java:61) ~[kryo-3.0.1.jar:na]
	at ameba.cache.util.KryoSerializer.asObject(KryoSerializer.java:82) ~[ameba-cache-core-0.1.7-20150612.185233-88.jar:na]
	at ameba.cache.util.Serializations.asObject(Serializations.java:32) ~[ameba-cache-core-0.1.7-20150612.185233-88.jar:na]
	at ameba.cache.util.Serializations.asObject(Serializations.java:38) ~[ameba-cache-core-0.1.7-20150612.185233-88.jar:na]
	at ameba.cache.Cache.get(Cache.java:365) ~[ameba-cache-core-0.1.7-20150612.185233-88.jar:na]
	at ameba.http.session.CacheSession.refresh(CacheSession.java:113) ~[ameba-session-0.1.7-20150612.180847-61.jar:na]
	at ameba.http.session.CacheSession.isInvalid(CacheSession.java:74) ~[ameba-session-0.1.7-20150612.180847-61.jar:na]
	at ameba.http.session.SessionFilter.filter(SessionFilter.java:68) ~[ameba-session-0.1.7-20150612.180847-61.jar:na]
	at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:132) ~[jersey-server-2.18.jar:na]
	at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:68) ~[jersey-server-2.18.jar:na]
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:197) ~[jersey-common-2.18.jar:na]
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:300) ~[jersey-server-2.18.jar:na]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [jersey-common-2.18.jar:na]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [jersey-common-2.18.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [jersey-common-2.18.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [jersey-common-2.18.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [jersey-common-2.18.jar:na]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [jersey-common-2.18.jar:na]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:291) [jersey-server-2.18.jar:na]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1140) [jersey-server-2.18.jar:na]
	at ameba.container.grizzly.server.http.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:150) [ameba-container-grizzly-0.1.7-20150528.081010-13.jar:na]
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [grizzly-http-server-2.3.20.jar:2.3.20]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591) [grizzly-framework-2.3.20.jar:2.3.20]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571) [grizzly-framework-2.3.20.jar:2.3.20]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_80]
Caused by: java.lang.ClassNotFoundException: ameba.http.session.SessionStorejava.lang.String
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[na:1.7.0_80]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[na:1.7.0_80]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_80]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[na:1.7.0_80]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[na:1.7.0_80]
	at ameba.dev.classloading.ReloadClassLoader.loadClass(ReloadClassLoader.java:158) ~[ameba-dev-0.1.7-20150611.090831-67.jar:0.1.7-SNAPSHOT]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[na:1.7.0_80]
	at java.lang.Class.forName0(Native Method) ~[na:1.7.0_80]
	at java.lang.Class.forName(Class.java:278) ~[na:1.7.0_80]
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:154) ~[kryo-3.0.1.jar:na]
	... 29 common frames omitted
```

version : 3.0.1
source code https://github.com/icode/ameba-cache/blob/master/core/src/main/java/ameba/cache/util/KryoSerializer.java

**Comment by magro** [comment]
Why do you think this is related to kryo-serializers? I'd think it's more related to kryo and would have a better home at the kryo mailing list.

**Comment by icode** [comment]
@magro kryo get class name is error

**Comment by icode** [comment]
one first error, and second time is ok.

Some time get Object from ehcache thow error
```
try {
    KryoSerializer.asObject(bytes);//throw error
} cache(Exception e) {
    KryoSerializer.asObject(bytes);//is ok
}
```

**Comment by magro** [comment]
Can you provide a reproducable test case?
Am 12.06.2015 23:12 schrieb "icode" <notifications@github.com>:

**Comment by icode** [comment]
Sorry, I can't find the law for this error, I'm use for http session serialize

**Comment by magro** [comment]
You should check where the class comes from (same jvm, same class loader?),
perhaps you have to implement you own class resolver.
Am 12.06.2015 23:16 schrieb "icode" <notifications@github.com>:

**Comment by magro** [comment]
For the case that you need a custom class resolver you could check this:
https://github.com/magro/kryo-serializers/blob/master/src/test/java/de/javakaffee/kryoserializers/cglib/CGLibProxySerializerTest.java
Am 13.06.2015 07:55 schrieb "Martin Grotzke" <martin.grotzke@googlemail.com

**Comment by icode** [comment]
Sorry, this seam Kryo issue, i commit error

**Comment by magro** [comment]
Ok
