### ISSUE TITLE
not able to deploy mule app 

### ISSUE THREAD

**Issue by sheedesh** [magro/kryo-serializers#52]
ERROR 2016-06-27 14:52:34,450 [main] org.mule.module.launcher.application.DefaultMuleApplication: null
java.lang.StackOverflowError
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:127) ~[kryo-shaded-3.0.1.jar:?]
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:667) ~[kryo-shaded-3.0.1.jar:?]
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:778) ~[kryo-shaded-3.0.1.jar:?]
	at de.javakaffee.kryoserializers.UnmodifiableCollectionsSerializer.read(UnmodifiableCollectionsSerializer.java:71) ~[kryo-serializers-0.29.jar:?]
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:787) ~[kryo-shaded-3.0.1.jar:?]
	at de.javakaffee.kryoserializers.UnmodifiableCollectionsSerializer.read(UnmodifiableCollectionsSerializer.java:71) ~[kryo-serializers-0.29.jar:?]
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:787) ~[kryo-shaded-3.0.1.jar:?]
	at de.javakaffee.kryoserializers.UnmodifiableCollectionsSerializer.read(UnmodifiableCollectionsSerializer.java:71) ~[kryo-serializers-0.29.jar:?]
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:787) ~[kryo-shaded-3.0.1.jar:?]
	at de.javakaffee.kryoserializers.UnmodifiableCollectionsSerializer.read(UnmodifiableCollectionsSerializer.java:71) ~[kryo-serializers-0.29.jar:?]
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:787) ~[kryo-shaded-3.0.1.jar:?]
	at de.javakaffee.kryoserializers.UnmodifiableCollectionsSerializer.read(UnmodifiableCollectionsSerializer.java:71) ~[kryo-serializers-0.29.jar:?]
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:787) ~[kryo-shaded-3.0.1.jar:?]
	at de.javakaffee.kryoserializers.UnmodifiableCollectionsSerializer.read(UnmodifiableCollectionsSerializer.java:71) ~[kryo-serializers-0.29.jar:?]
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:787) ~[kryo-shaded-3.0.1.jar:?]
	at de.javakaffee.kryoserializers.UnmodifiableCollectionsSerializer.read(UnmodifiableCollectionsSerializer.java:71) ~[kryo-serializers-0.29.jar:?]
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:787) ~[kryo-shaded-3.0.1.jar:?]
	at de.javakaffee.kryoserializers.UnmodifiableCollectionsSerializer.read(UnmodifiableCollectionsSerializer.java:71) ~[kryo-serializers-0.29.jar:?]
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:787) ~[kryo-shaded-3.0.1.jar:?]
	at de.javakaffee.kryoserializers.UnmodifiableCollectionsSerializer.read(UnmodifiableCollectionsSerializer.java:71) ~[kryo-serializers-0.29.jar:?]
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:787) ~[kryo-shaded-3.0.1.jar:?]
	at de.javakaffee.kryoserializers.UnmodifiableCollectionsSerializer.read(UnmodifiableCollectionsSerializer.java:71) ~[kryo-serializers-0.29.jar:?]
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:787) ~[kryo-shaded-3.0.1.jar:?]
	at de.javakaffee.kryoserializers.UnmodifiableCollectionsSerializer.read(UnmodifiableCollectionsSerializer.java:71) ~[kryo-serializers-0.29.jar:?]
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:787) ~[kryo-shaded-3.0.1.jar:?]
	at de.javakaffee.kryoserializers.UnmodifiableCollectionsSerializer.read(UnmodifiableCollectionsSerializer.java:71) ~[kryo-serializers-0.29.jar:?]
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:787) ~[kryo-shaded-3.0.1.jar:?]
	at de.javakaffee.kryoserializers.UnmodifiableCollectionsSerializer.read(UnmodifiableCollectionsSerializer.java:71) ~[kryo-serializers-0.29.jar:?]
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:787) ~[kryo-shaded-3.0.1.jar:?]
	at de.javakaffee.kryoserializers.UnmodifiableCollectionsSerializer.read(UnmodifiableCollectionsSerializer.java:71) ~[kryo-serializers-0.29.jar:?]
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:787) ~[kryo-shaded-3.0.1.jar:?]
	at de.javakaffee.kryoserializers.UnmodifiableCollectionsSerializer.read(UnmodifiableCollectionsSerializer.java:71) ~[kryo-serializers-0.29.jar:?]

**Comment by magro** [comment]
How can this be reproduced?
