### ISSUE TITLE
ConcurrentModificationException when serializing using the JdkProxySerializer

### ISSUE THREAD

**Issue by guyman** [magro/kryo-serializers#58]
```
2016-08-22 13:59:06,195 | ERROR | ult-dispatcher-2 | OneForOneStrategy                | 172 - com.typesafe.akka.slf4j - 2.4.7 | java.util.ConcurrentModificationException
Serialization trace:
classes (sun.misc.Launcher$AppClassLoader)
parent (org.eclipse.core.runtime.internal.adaptor.ContextFinder)
contextClassLoader (java.lang.Thread)
threads (java.lang.ThreadGroup)
groups (java.lang.ThreadGroup)
group (org.eclipse.osgi.framework.eventmgr.EventManager$EventThread)
thread (org.eclipse.osgi.framework.eventmgr.EventManager)
bundleFileCloserManager (org.eclipse.osgi.baseadaptor.bundlefile.MRUBundleFileList)
mruList (org.eclipse.osgi.baseadaptor.bundlefile.ZipBundleFile)
bundleFile (org.eclipse.osgi.internal.baseadaptor.SystemBundleData)
bundledata (org.eclipse.osgi.framework.internal.core.InternalSystemBundle)
bundle (org.eclipse.osgi.framework.internal.core.SystemBundleActivator)
activator (org.eclipse.osgi.framework.internal.core.BundleContextImpl)
context (org.eclipse.osgi.baseadaptor.BaseAdaptor)
adaptor (org.eclipse.osgi.baseadaptor.BaseData)
bundledata (org.eclipse.osgi.framework.internal.core.BundleHost)
bundle (org.eclipse.osgi.internal.loader.BundleLoader)
delegate (org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader)
referent (java.lang.ref.WeakReference)
clref (javassist.LoaderClassPath)
path (javassist.ClassPathList)
next (javassist.ClassPathList)
next (javassist.ClassPathList)
next (javassist.ClassPathList)
next (javassist.ClassPathList)
next (javassist.ClassPathList)
next (javassist.ClassPathList)
next (javassist.ClassPathList)
next (javassist.ClassPathList)
next (javassist.ClassPathList)
next (javassist.ClassPathList)
next (javassist.ClassPathList)
next (javassist.ClassPathList)
pathList (javassist.ClassPoolTail)
source (javassist.ClassPool)
classPool (org.opendaylight.yangtools.sal.binding.generator.util.JavassistUtils)
javassist (org.opendaylight.yangtools.binding.data.codec.gen.impl.StreamWriterGenerator)
generator (org.opendaylight.yangtools.binding.data.codec.impl.BindingNormalizedNodeCodecRegistry)
registry (org.opendaylight.yangtools.binding.data.codec.impl.BindingCodecContext)
factory (org.opendaylight.yangtools.binding.data.codec.impl.DataContainerCodecPrototype)
prototype (org.opendaylight.yangtools.binding.data.codec.impl.KeyedListNodeCodecContext)
context (org.opendaylight.yangtools.binding.data.codec.impl.LazyDataObject)
cachedData (org.opendaylight.yangtools.binding.data.codec.impl.LazyDataObject)
augmentation (org.opendaylight.yang.gen.v1.urn.tbd.params.xml.ns.yang.network.topology.rev131021.network.topology.topology.node.TerminationPointBuilder$TerminationPointImpl)
input (org.opendaylight.newfederation.impl.DTOFederatedObject)
com.esotericsoftware.kryo.KryoException: java.util.ConcurrentModificationException
Serialization trace:
classes (sun.misc.Launcher$AppClassLoader)
parent (org.eclipse.core.runtime.internal.adaptor.ContextFinder)
contextClassLoader (java.lang.Thread)
threads (java.lang.ThreadGroup)
groups (java.lang.ThreadGroup)
group (org.eclipse.osgi.framework.eventmgr.EventManager$EventThread)
thread (org.eclipse.osgi.framework.eventmgr.EventManager)
bundleFileCloserManager (org.eclipse.osgi.baseadaptor.bundlefile.MRUBundleFileList)
mruList (org.eclipse.osgi.baseadaptor.bundlefile.ZipBundleFile)
bundleFile (org.eclipse.osgi.internal.baseadaptor.SystemBundleData)
bundledata (org.eclipse.osgi.framework.internal.core.InternalSystemBundle)
bundle (org.eclipse.osgi.framework.internal.core.SystemBundleActivator)
activator (org.eclipse.osgi.framework.internal.core.BundleContextImpl)
context (org.eclipse.osgi.baseadaptor.BaseAdaptor)
adaptor (org.eclipse.osgi.baseadaptor.BaseData)
bundledata (org.eclipse.osgi.framework.internal.core.BundleHost)
bundle (org.eclipse.osgi.internal.loader.BundleLoader)
delegate (org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader)
referent (java.lang.ref.WeakReference)
clref (javassist.LoaderClassPath)
path (javassist.ClassPathList)
next (javassist.ClassPathList)
next (javassist.ClassPathList)
next (javassist.ClassPathList)
next (javassist.ClassPathList)
next (javassist.ClassPathList)
next (javassist.ClassPathList)
next (javassist.ClassPathList)
next (javassist.ClassPathList)
next (javassist.ClassPathList)
next (javassist.ClassPathList)
next (javassist.ClassPathList)
next (javassist.ClassPathList)
pathList (javassist.ClassPoolTail)
source (javassist.ClassPool)
classPool (org.opendaylight.yangtools.sal.binding.generator.util.JavassistUtils)
javassist (org.opendaylight.yangtools.binding.data.codec.gen.impl.StreamWriterGenerator)
generator (org.opendaylight.yangtools.binding.data.codec.impl.BindingNormalizedNodeCodecRegistry)
registry (org.opendaylight.yangtools.binding.data.codec.impl.BindingCodecContext)
factory (org.opendaylight.yangtools.binding.data.codec.impl.DataContainerCodecPrototype)
prototype (org.opendaylight.yangtools.binding.data.codec.impl.KeyedListNodeCodecContext)
context (org.opendaylight.yangtools.binding.data.codec.impl.LazyDataObject)
cachedData (org.opendaylight.yangtools.binding.data.codec.impl.LazyDataObject)
augmentation (org.opendaylight.yang.gen.v1.urn.tbd.params.xml.ns.yang.network.topology.rev131021.network.topology.topology.node.TerminationPointBuilder$TerminationPointImpl)
input (org.opendaylight.newfederation.impl.DTOFederatedObject)
at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:101)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:518)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:552)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:518)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:552)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:518)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:628)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:366)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:307)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:552)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:518)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:628)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:366)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:307)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:552)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:518)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:552)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:518)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:552)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:518)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:552)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:518)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:552)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:518)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:552)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:518)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:552)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:518)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:552)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:518)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:552)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:518)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:552)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:518)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:552)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80)[332:com.esotericsoftware.kryo-shaded:3.0.3]
.....
at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:552)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:518)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:628)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at de.javakaffee.kryoserializers.JdkProxySerializer.write(JdkProxySerializer.java:52)[334:de.javakaffee.kryo-serializers:0.38.0]
        at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:628)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:100)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:40)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:628)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:113)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:39)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:552)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:518)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:628)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at de.javakaffee.kryoserializers.JdkProxySerializer.write(JdkProxySerializer.java:52)[334:de.javakaffee.kryo-serializers:0.38.0]
        at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:628)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.serializers.DefaultSerializers$CollectionsSingletonMapSerializer.write(DefaultSerializers.java:588)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.serializers.DefaultSerializers$CollectionsSingletonMapSerializer.write(DefaultSerializers.java:580)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:552)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:518)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:552)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:518)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:534)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at org.opendaylight.newfederation.transform.FederationPublisherActor.onReceive(FederationPublisherActor.java:53)[335:org.opendaylight.federation.new-federation:0.1.0.SNAPSHOT]
        at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:165)[171:com.typesafe.akka.actor:2.4.7]
        at akka.actor.Actor$class.aroundReceive(Actor.scala:484)[171:com.typesafe.akka.actor:2.4.7]
        at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:95)[171:com.typesafe.akka.actor:2.4.7]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)[171:com.typesafe.akka.actor:2.4.7]
        at akka.actor.ActorCell.invoke(ActorCell.scala:495)[171:com.typesafe.akka.actor:2.4.7]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)[171:com.typesafe.akka.actor:2.4.7]
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)[171:com.typesafe.akka.actor:2.4.7]
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)[171:com.typesafe.akka.actor:2.4.7]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)[167:org.scala-lang.scala-library:2.11.8.v20160304-115712-1706a37eb8]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)[167:org.scala-lang.scala-library:2.11.8.v20160304-115712-1706a37eb8]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)[167:org.scala-lang.scala-library:2.11.8.v20160304-115712-1706a37eb8]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)[167:org.scala-lang.scala-library:2.11.8.v20160304-115712-1706a37eb8]
Caused by: java.util.ConcurrentModificationException
        at java.util.Vector$Itr.checkForComodification(Vector.java:1184)[:1.8.0_91]
        at java.util.Vector$Itr.next(Vector.java:1137)[:1.8.0_91]
        at com.esotericsoftware.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:92)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:40)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:552)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80)[332:com.esotericsoftware.kryo-shaded:3.0.3]
        ... 166 more

```

**Comment by magro** [comment]
The Serialization trace shows that a classloader is serialized - definitely too much. Going through the long trace I'd guess that something between input and factory should be the last thing that should be serialized - but only you can know what's expected there. Perhaps you need to write a custom serializer for one of the problematic classes, to have a clear boundary. 

Based on the provided information it's impossible to say if there's a bug in the JdkProxySerializer or not (the bug report doesn't even show that / how you're using it ;-)).
Please provide a reproducable sample that allows to reproduce the issue if you want to get this analyzed.

**Comment by guyman** [comment]
Got it. Thank you very much for the elaborated answer:)
