### ISSUE TITLE
UnmodifieableCollectionsSerializer: NPE when serializing list created by `Arrays.asList()`

### ISSUE THREAD

**Issue by jerrinot** [magro/kryo-serializers#66]
This should be enough to reproduce it:
```java
    public final class ClassWithUnmodifieableList {
        private List<String> names;

        public ClassWithUnmodifieableList(String...names) {
                this.names = Collections.unmodifiableList(Arrays.asList(names));
        }
    }
```

I'm getting this exception when attempting to deserialize this class:
```
com.hazelcast.nio.serialization.HazelcastSerializationException: com.esotericsoftware.kryo.KryoException: java.lang.NullPointerException
Serialization trace:
names (info.jerrinot.subzero.TestCustomerSerializers$ClassWithUnmodifieableList)

	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleException(SerializationUtil.java:61)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:178)
	at com.hazelcast.map.impl.proxy.MapProxySupport.toObject(MapProxySupport.java:1067)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.get(MapProxyImpl.java:94)
	at info.jerrinot.subzero.TestCustomerSerializers.testSpecialRegistrationRegisteredInDefaultConfigFile(TestCustomerSerializers.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: com.esotericsoftware.kryo.KryoException: java.lang.NullPointerException
Serialization trace:
names (info.jerrinot.subzero.TestCustomerSerializers$ClassWithUnmodifieableList)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:144)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:540)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:813)
	at info.jerrinot.subzero.internal.strategy.GlobalKryoStrategy.readObject(GlobalKryoStrategy.java:28)
	at info.jerrinot.subzero.internal.strategy.KryoStrategy.read(KryoStrategy.java:79)
	at info.jerrinot.subzero.AbstractSerializer.read(AbstractSerializer.java:30)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:46)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:172)
	... 32 more
Caused by: java.lang.NullPointerException
	at java.util.Arrays$ArrayList.size(Arrays.java:3818)
	at java.util.AbstractList.add(AbstractList.java:108)
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:134)
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:40)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:813)
	at de.javakaffee.kryoserializers.UnmodifiableCollectionsSerializer.read(UnmodifiableCollectionsSerializer.java:71)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:731)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
	... 39 more
```

when I change it to
```java
        public ClassWithUnmodifieableList(String...names) {
            ArrayList<String> strings = new ArrayList<>(names.length);
            for (String name : names) {
                strings.add(name);
            }
            this.names = Collections.unmodifiableList(strings);
        }
```
then everything works as expected;

**Comment by magro** [comment]
Have you registered the ArraysAsListSerialiser?

**Comment by jerrinot** [comment]
oh, I did not. let me try it!

**Comment by jerrinot** [comment]
ok, it's working now. I missed the extra serializer registration. 
Many thanks for a quick help!

**Comment by magro** [comment]
You're welcome!
