### ISSUE TITLE
Missing serializer for Guava JdkBackedImmutable* classes

### ISSUE THREAD

**Issue by matt-preston** [magro/kryo-serializers#92]
Guava 24.1 introduced new implementations of `ImmutableSet`, `ImmutableMultiset`, `ImmutableMap` and `ImmutableBiMap`.  These new implementations do not get registered with kryo by the guava support classes in kryo-serializer.

e.g. `ImmutableMapSerializer` does not register a serializer for `com.google.common.collect.JdkBackedImmutableMap`

Serializing Guava ImmutableMap instances with `kryo.setRegistrationRequired(true)` can lead to Exceptions like this:

```
java.lang.IllegalArgumentException: Class is not registered: com.google.common.collect.JdkBackedImmutableMap
Note: To register this class use: kryo.register(com.google.common.collect.JdkBackedImmutableMap.class);
    at com.esotericsoftware.kryo.Kryo.getRegistration(Kryo.java:503)
    at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:557)
```

**Comment by magro** [comment]
Thanks for reporting! Do you want to submit a fix for this?
